package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"time"
)

type BullsData struct {
	Date           string                 `json:"date"`
	BullsBasic     map[string]interface{} `json:"bulls_basic"`
	BullsAdvanced  map[string]interface{} `json:"bulls_advanced"`
	Calculated     map[string]interface{} `json:"calculated"`
	GameToday      interface{}            `json:"game_today"`
	NextGame       interface{}            `json:"next_game"`
	Injuries       []interface{}          `json:"injuries"`
}

func main() {
	// Serve static JSON file
	http.HandleFunc("/api/bulls-today", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Access-Control-Allow-Origin", "*") // Allow React to fetch from anywhere

		// Read the JSON file generated by Python
		file, err := os.Open("bulls_team_efficiency.json")
		if err != nil {
			http.Error(w, "Could not read data", http.StatusInternalServerError)
			return
		}
		defer file.Close()

		byteValue, _ := ioutil.ReadAll(file)
		var data BullsData
		json.Unmarshal(byteValue, &data)

		// Optional: Add server timestamp
		data.Date = time.Now().Format("2006-01-02 15:04")

		json.NewEncoder(w).Encode(data)
	})

	// Simple root endpoint for testing
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Bulls Efficiency API is running! Use /api/bulls-today")
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080" // default local port
	}

	fmt.Printf("Server starting on :%s\n", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}